export const CREATE_TASK = "CREATE_TASK"
export const GET_TASK = "GET_TASK"
export const GET_DONE = "GET_DONE"
export const IS_DONE = "IS_DONE"
export const EDIT_TASK = "EDIT_TASK"
export const DELETE_TASK = "DELETE_TASK"